# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [2]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [3]:
#todo: 

nnumeros = np.arange(10)

print("array: ", nnumeros)


#nota: np.arange, genera un array de números, viene de "array" + "range"


array:  [0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [8]:
#todo:

ceros = np.zeros(5)

ceros[2] = 5

print(ceros)

[0. 0. 5. 0. 0.]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [ ]:
#todo: 

matriz = np.random.randint(0,2,size=(3,3))

print(matriz)


#nota: genera n enteros aleatorios, donde se ubica los numeros qe se quieren incluir desde el 0 (incluido), al 2 (no incluido), en este caso qeremos generar una matriz, y con size, decimos a la funcion qe qeremos una de 3x3

[[0 0 0]
 [1 1 1]
 [0 0 0]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [3]:
#todo:

arr = np.array([10,20,30,40,50])

suma = arr + 5

numero = randint(0,1000000)

resultado = suma * numero

print("numero aleatorio elegido: ", numero)
print(resultado)

numero aleatorio elegido:  121891
[1828365 3047275 4266185 5485095 6704005]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [ ]:
#todo:

matriz= np.identity(4, dtype=int)

print (matriz)

#nota: dtype es "tipo de dato"

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [ ]:
#todo: 

array = np.arange(0,21,2)

numero = randint(1, 1000000)

suma= array + numero

resta= array - numero

multiplicacion = array * numero

division= array / numero

print("numero elegido:",numero,"suma:",suma,"resta:",resta,"multiplicacion:",multiplicacion,"division:",division)


numero elegido: 561289 suma: [561289 561291 561293 561295 561297 561299 561301 561303 561305 561307
 561309] resta: [-561289 -561287 -561285 -561283 -561281 -561279 -561277 -561275 -561273
 -561271 -561269] multiplicacion: [       0  1122578  2245156  3367734  4490312  5612890  6735468  7858046
  8980624 10103202 11225780] division: [0.00000000e+00 3.56322679e-06 7.12645357e-06 1.06896804e-05
 1.42529071e-05 1.78161339e-05 2.13793607e-05 2.49425875e-05
 2.85058143e-05 3.20690411e-05 3.56322679e-05]
